TOTAL_TIME: 30d
INTERVAL_TIME_TOTAL: 36h
DEVIATION_TIME: 0m
INTERVAL_COUNT: 10
FLASK_PORT: 5005
ALLOWED_ORIGINS: ['http://192.168.1.1', 'https://somewebsite.com']
GROUPME_ADMIN_USER_ID: 1234
GROUPME_BOT_ID: 4567
DATABASE_URL: sqlite:///button_data.db